version: '3.4'

services:
  client:
    build:
      context: apps/client-remix
      dockerfile: Dockerfile
    environment:
      - PORT=${CLIENT_PORT}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - CLERK_PUBLISHABLE_KEY=${CLERK_PUBLISHABLE_KEY}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - sc2iqnetwork

networks:
  sc2iqnetwork:
